---
title: "ds3001_week3_lab_graph3"
author: "Claire Dozier"
date: "9/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load data
str(faithful)
```

```{r}
# Data Visualization
library(ggplot2)
ggplot(faithful, aes(x = waiting)) + geom_histogram(binwidth = 3, fill = 'darkmagenta') 

```

```{r}
# Adding labels
library(ggplot2)
ggplot(faithful, aes(x = waiting)) + geom_histogram(binwidth = 3, fill = 'darkmagenta') +xlab('Waiting (time it took for eruption)')
```


```{r}
# Adding labels
library(ggplot2)
ggplot(faithful, aes(x = waiting)) + geom_histogram(binwidth = 3, fill = 'darkmagenta') +xlab('Waiting (time it took for eruption)')  + ggtitle("Distribution of Geyser Eruption Waiting Times")
```

```{r}
# Adding title
library(ggplot2)
ggplot(faithful, aes(x = waiting)) + geom_histogram(binwidth = 3, fill = 'darkmagenta') +xlab('Waiting (time it took for eruption)')  + ggtitle("Distribution of Geyser Eruption Waiting Times")
```
